### ISSUE TITLE
Installing with zef, does not result in a working `mi6` binary on Linux

### ISSUE THREAD

**Issue by samcv** [skaji/mi6#16]
When you install it using `zef install .` things work fine, but installing as `zef install App::Mi6` fails
```
===SORRY!=== Error while compiling /home/samantha/perl6/share/perl6/site/resources/19DFC05B99EC4E218A1A8D9A1B966919724DE593
Two terms in a row
at /home/samantha/perl6/share/perl6/site/resources/19DFC05B99EC4E218A1A8D9A1B966919724DE593:1
------> @⏏ perl6 %~dpn0 %*
    expecting any of:
        infix
        infix stopper
        statement end
        statement modifier
        statement modifier loop

```

**Comment by skaji** [comment]
Do you have any idea?

**Comment by ugexe** [comment]
The root cause of the issue was resolved here: https://github.com/skaji/mi6/issues/14

However - because there is no version in the `META6.json` (`*` is treated as 0 in rakudo for module versions) I suspect @samcv is getting a cached version that does not have the fix since zef is unaware that the versions being the same isn't true. By doing `zef install $path` or `zef install $url` you bypass the caching mechanism, so were able to install the *actual* latest version.

While its possible the cache could take into account `git rev-list` output when handling modules with version `*` that solution is very git specific and doesn't work for other content storage types. And after conversations with @niner in #perl6-dev in the past I suspect use of `"version" : "*"` will simply have to be discouraged. e.g. version declarations in **META6.json** must be concrete, and non specific versions/ranges such as `:ver<*>`/`:ver<1.*.0>` should only be used when **requesting** a name (such as `use Foo:ver<1>` or `zef install "Foo:ver<1>"`)

**Comment by skaji** [comment]
hmm
```
❯ zef install --force --/test App::Mi6
===> Searching for: App::Mi6
===> Installing: App::Mi6

2 bin/ scripts [mi6 mi6.bat] installed to:
/Users/skaji/env/rakudobrew/moar-nom/install/share/perl6/site/bin

❯ cat /Users/skaji/env/rakudobrew/moar-nom/install/share/perl6/site/bin/mi6
#!/usr/bin/env perl6
sub MAIN(:$name is copy, :$auth, :$ver, *@, *%) {
    shift @*ARGS if $name;
    shift @*ARGS if $auth;
    shift @*ARGS if $ver;
    $name //= 'App::Mi6';
    my @installations = $*REPO.repo-chain.grep(CompUnit::Repository::Installable);
    my @binaries = flat @installations.map: { .files('bin/mi6.bat', :$name, :$auth, :$ver) };
    unless +@binaries {
        @binaries = flat @installations.map: { .files('bin/mi6.bat', :$name) };
        if +@binaries {
            note q:to/SORRY/;
...
```

**Comment by skaji** [comment]
https://github.com/skaji/mi6/issues/17#issuecomment-298261106
I see.

**Comment by skaji** [comment]
I will specify version.

@ugexe 
I don't know the relationship between version in META6.json and versions for modules/classes (or compilation units).
Is this documented somewhere?

**Comment by ugexe** [comment]
Right now the META6.json `"version" : "1.1"` means all code included in the distribution is version 1.1. What this doesn't address is how to version specific namespaces... a naive answer would be to change provides to be like `"provides" : { "Foo" : "lib/Foo.pm6", "Foo::Bar:ver<1.0>" : "lib/FooOld.pm6" }`.

The simple answer is, for CompUnit::Repository::Installation, two distributions are the same *if* their META6.json has a matching name, auth, and version field.

The more complex answer? For CompUnit::Repository::FileSystem two distributions are the same if they have the same *name* only. And CompUnit::Repository::AbsolutePath if they have the same *path*. These two are what you get from -Ilib or `use lib "..."` or `require "/home/foo/bar"`. I mention these because these are the CURs (CompUnit::Repository-s) most people develop against, but almost everyone else will use your code from a CURI (CompUnit::Repository::Installation).

**Comment by skaji** [comment]
@ugexe thanks! This helps a lot.

So if one just want to declare all code included in the distribution `Foo::Bar` are version 1.1 then:
```
# META6.json
{
  "name": "Foo::Bar",
  "version": "1.1",
  "provides": {
    "Foo::Bar": "lib/Foo/Bar.pm6",
    "Foo::Bar::Baz": "lib/Foo/Bar.pm6",
    "Foo::Bar::Qux": "lib/Foo/Bar/Qux.pm6"
  },
  ...
}
```
Is this correct?

> two distributions are the same if their META6.json has a matching name, auth, and version field.

Oh, https://design.perl6.org/S22.html does not say META6.json can contains "auth" field.

**Comment by ugexe** [comment]
Yes that is correct. And the design documents are not a (pardon the pun) authority on spec. You can however see it mentioned in s22 as https://design.perl6.org/S22.html#auth
